package test.myfisttest.fristtest.Entity;

public class Privateletter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.RECEIVER_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.SEND_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private Long sendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.GMT_CREATE
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.STATUS
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRIVATELETTER.CONTENT
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.ID
     *
     * @return the value of PRIVATELETTER.ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.ID
     *
     * @param id the value for PRIVATELETTER.ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.RECEIVER_ID
     *
     * @return the value of PRIVATELETTER.RECEIVER_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.RECEIVER_ID
     *
     * @param receiverId the value for PRIVATELETTER.RECEIVER_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.SEND_ID
     *
     * @return the value of PRIVATELETTER.SEND_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public Long getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.SEND_ID
     *
     * @param sendId the value for PRIVATELETTER.SEND_ID
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.GMT_CREATE
     *
     * @return the value of PRIVATELETTER.GMT_CREATE
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.GMT_CREATE
     *
     * @param gmtCreate the value for PRIVATELETTER.GMT_CREATE
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.STATUS
     *
     * @return the value of PRIVATELETTER.STATUS
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.STATUS
     *
     * @param status the value for PRIVATELETTER.STATUS
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRIVATELETTER.CONTENT
     *
     * @return the value of PRIVATELETTER.CONTENT
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRIVATELETTER.CONTENT
     *
     * @param content the value for PRIVATELETTER.CONTENT
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}