package test.myfisttest.fristtest.Mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import test.myfisttest.fristtest.Entity.Privateletter;
import test.myfisttest.fristtest.Entity.PrivateletterExample;

public interface PrivateletterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    long countByExample(PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int deleteByExample(PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int insert(Privateletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int insertSelective(Privateletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    List<Privateletter> selectByExampleWithBLOBsWithRowbounds(PrivateletterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    List<Privateletter> selectByExampleWithBLOBs(PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    List<Privateletter> selectByExampleWithRowbounds(PrivateletterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    List<Privateletter> selectByExample(PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    Privateletter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Privateletter record, @Param("example") PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Privateletter record, @Param("example") PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByExample(@Param("record") Privateletter record, @Param("example") PrivateletterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByPrimaryKeySelective(Privateletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Privateletter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRIVATELETTER
     *
     * @mbg.generated Sat Aug 24 15:02:41 CST 2019
     */
    int updateByPrimaryKey(Privateletter record);
}